name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install
        run: make install
        env:
          CI: true
      - name: Prepare
        run: make prepare
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
